name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci || echo "No dependencies to install"

      - name: Ensure public directory exists
        run: mkdir -p public/image || echo "No public/image directory"

      - name: Move image assets if exist
        run: |
          if [ -d "image" ]; then
            mkdir -p public/image
            cp -r image/* public/image/
          fi

      - name: Run build
        run: npm run build || echo "Build failed!"

      - name: Debug build output
        run: ls -R build || echo "No build directory found"

      - name: Copy public assets to build
        run: cp -r public/* build/ || echo "No public directory to copy"

      - name: Debug final build output
        run: ls -R build || echo "No final build directory found"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
